project:
  title: "Portfolio"
  output-dir: docs
  type: website

execute:
  freeze: true

website:
  title: "Portfolio"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/mbdavid2
      - icon: google
        href: https://scholar.google.com/citations?hl=en&user=7gicQ2kAAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/mbdavid2/
      - icon: facebook
        href: ./images/komoLoZupo.gif

format:
  html:
    theme: litera
    css: styles.css
    toc: true

